accounts/urls.py
from django.urls import path 
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'
urlpatterns = [
   path('user/signup/', views.SignUpView.as_view(), name='signup'),
   path('u/<slug:username>/detail/', views.DetailAccountView.as_view(), name='account_detail'),
   path('u/<slug:username>/update/', views.UpdateAccountView.as_view(), name='account_update'),
   path('u/<slug:username>/following/', views.FollowingListView.as_view(), name='following'),
   path('u/<slug:username>/followers/', views.FollowersListView.as_view(), name='followers'),
   
 ]

cloned/urls.py
from django.urls import path
from . import views

app_name = 'cloned'
urlpatterns = [
    path('', views.TweetListView.as_view(), name='home'),
    path('add/', views.TweetAddView.as_view(), name='add_tweet'),
    path('tweet/<int:pk>/like/', views.TweetLikeView, name='tweet_like'),
    path('tweet/<int:pk>/comment/', views.CommentAddView.as_view(), name='add_comment'),
    path('tweet/<int:pk>/edit', views.TweetEditView.as_view(), name='edit_tweet'),
    path('tweet/<int:pk>/delete', views.TweetDeleteView.as_view(), name='delete_tweet'),
    path('tweet/<int:pk>/like', views.TweetLikeView, name='like'),
    path('tweet/<int:pk>/unlike', views.TweetUnlikeView, name='unlike')

]

twitter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('cloned.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

cloned/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from profiles.models import Profile
# Create your models here

class Tweet(models.Model):
    #name of the person who posted a tweet

    author  = models.ForeignKey(
        'accounts.User',
        related_name='tweets',
        on_delete=models.CASCADE,)

    #The date a tweet is posted
    date_created = models.DateTimeField(auto_now_add=True)
    #The body of the tweet
    tweet = models.TextField(max_length=150)

    tags = models.ManyToManyField(
        'cloned.Tag',
        related_name='tweets')
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Tweets'
        ordering = ['-date_created', ]
    
    
    def get_absolute_url(self):
        return reverse('cloned:home')

    def __str__(self):
        return self.tweet

class Comment(models.Model):
    #make the relationship btw the teeet and the comment
    comment_for = models.ForeignKey(
        'cloned.Tweet',
        on_delete=models.CASCADE,
        related_name='comments')

    #name/author of the person commenting
    comment_author = models.ForeignKey(
        'accounts.User',
        related_name='comments',
        on_delete=models.CASCADE)
    #body of the comment
    comment_text = models.TextField(max_length=250)
    #the nunber of likes a tweet has
    #comment_likes = models.IntegerField(default=0)

    def __str__(self):
        return self.comment_text

class Like(models.Model):
    tweet = models.ForeignKey(Tweet,
        related_name='liked_tweet',
        on_delete=models.CASCADE)
    user = models.ForeignKey('accounts.User',
        related_name='liker',
        on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)


    def like(self, tweet):
        """Like tweet is we are not alredy liking it"""
        self.tweet.add(tweet)

    def unlike(self, tweet):
        """Unlike tweet if we are already liking it"""
        self.tweet.remove(tweet)

    def has_liked(self, tweet):
        """retruns True if we have alreay liked a tweet, otherwise False"""
        return self.tweet.filter(pk=tweet.pk).exists()

    def __str__(self):
        return '{} : {}'.format(self.user, self.tweet)


class Tag(models.Model):
    tag = models.CharField(max_length=150)

    def __str__(self):
        return self.tag

cloned/forms.py
from django import forms
from .models import Tweet, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ['comment_author']
        fields = ('comment_text',)


class TweetForm(forms.ModelForm):
    class Meta:
        model = Tweet
        exclude = ['author']
        fields = ['tweet']

cloned/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.views import generic
from django.db.models import F
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from braces import views
from accounts.funcs import get_logon_user

from profiles.models import Profile
from .forms import CommentForm, TweetForm
from .models import Tweet, Comment, Like


class TweetListView(generic.ListView):
    template_name = 'cloned/home.html'
    context_object_name = 'tweets'

    def get_queryset(self):
        return Tweet.objects.all().order_by('-date_created')



class TweetAddView(views.LoginRequiredMixin, generic.edit.CreateView):
    model = Tweet
    template_name = 'cloned/add_tweet.html'
    form_class = TweetForm

    def form_valid(self, form):
        tweet = form.save(commit=False)
        tweet.author = Profile.objects.get(user=self.request.user)
        tweet.save()
        return HttpResponseRedirect(reverse('cloned:home'))


class TweetEditView(views.LoginRequiredMixin, generic.edit.UpdateView):
    model = Tweet
    fields = ['tweet']
    template_name = 'cloned/tweet_edit.html'
    context_object_name = 'tweet'
    success_url = reverse_lazy('cloned:home')


class TweetDeleteView(views.LoginRequiredMixin, generic.DeleteView):
    model = Tweet
    template_name = 'cloned/tweet_delete.html'
    success_url = reverse_lazy('cloned:home')



class CommentAddView(views.LoginRequiredMixin, generic.FormView):
    form_class = CommentForm
    template_name = 'cloned/add_comment.html'
    

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        tweet = get_object_or_404(Tweet, pk=kwargs.get('pk'))
        comments = tweet.comments.all()
        user = self.request.user
        is_liked = Like.objects.filter(tweet=tweet, user=user).exists()
        likes = Like.objects.filter(tweet=tweet).count()
        return render(request, self.template_name, {'form': form, 'tweet':tweet, 'comments':comments, 'likes':likes, 'is_liked':is_liked})

    def post(self, request, *args, **kwargs):
        tweet = get_object_or_404(Tweet, pk=kwargs.get('pk'))
        comments = tweet.comments.all()
        form = self.form_class(request.POST)
        comment = Comment(comment_text=form['comment_text'].value())
        comment.comment_for = tweet
        comment.comment_author = Profile.objects.get(user=self.request.user)
        if form.is_valid():
            add_comment_to_tweet = tweet.comments.add(comment, bulk=False)
            return HttpResponseRedirect(reverse('cloned:add_comment', args=(tweet.pk,)))
        return render(request, self.template_name, {'form': form})


@login_required
def TweetLikeView(request, *args, **kwargs):
    try:
        tweet = Tweet.objects.get(pk=kwargs['pk'])

        _, created = Like.objects.get_or_create(tweet=tweet, user=request.user)

        if not created:
            messages.warning(request, 'You\'ve already liked the tweet.')
    except Post.DoesNotExist:
        messages.warning(request, 'Tweet does not exist')

    return HttpResponseRedirect(reverse_lazy('cloned:add_comment',kwargs={'pk': kwargs['pk']}))


@login_required
def TweetUnlikeView(request, *args, **kwargs):
    try:
        like = Like.objects.get(tweet__pk=kwargs['pk'], user=request.user)
    except Like.DoesNotExist:
        messages.warning(request, 'You didn\'t like this tweet.')
    else:
        like.delete()

    return HttpResponseRedirect(reverse_lazy('cloned:add_comment', kwargs={'pk': kwargs['pk']}))



# def CommentAdd(request, pk):
#     tweet = get_object_or_404(Tweet, pk=pk)
#     comments = tweet.comment_set.all()
#     comment_form = CommentForm(request.POST or None)
#     if comment_form.is_valid():
#         comment = Comment(comment_author=comment_form['comment_author'].value(), comment_text=comment_form['comment_text'].value())
#         tweet_in = tweet.comment_set.add(comment, bulk=False)
#         return HttpResponseRedirect(reverse('cloned:add_comment', args=(tweet.pk,)))
#     return render(request, 'cloned/add_comment.html', {'tweet':tweet, 'comments':comments, 'form': comment_form})


# def tweet_like(request, pk):
#     # for k, v in kwargs.items():
#     #     if "pk" in k:
#     #         tweet_pk = v
#     try:
#        tweet = get_object_or_404(Tweet, pk=pk)
#     except (KeyError, Tweet.DoesNotExist):
#         return render(request, 'cloned/home.html')
#     else:
#         tweet.tweet_likes = F('tweet_likes') + 1
#         tweet.save()
#         return HttpResponseRedirect(reverse('cloned:home'))

cloned/templates/cloned/add_comment.html
{% extends 'cloned/base.html' %}
{% block title %}Comment on tweet{% endblock title %}

{% block content %}
<span><h3>{{ tweet.tweet }}</h3></span>
<span>
{% if is_liked  %}
  <a href="{% url 'cloned:unlike' tweet.pk %}"><button class="btn btn-primary" type="submit">
    Like <span class="badge">{{ likes }}</span>
  </button></a>
{% else %}
  <a href="{% url 'cloned:like' tweet.pk %}"><button class="btn btn-default" type="submit">
      Like <span class="badge">{{ likes }}</span>
  </button></a>
{% endif %}
</span>
{%if user == tweet.author %}
<span>
<div class="btn-group">
 <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Menu <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="{% url 'cloned:edit_tweet' tweet.pk %}">Edit</a></li>
    <li><a class="dropdown-item" href="{% url 'cloned:delete_tweet' tweet.pk %}">Delete</a></li>
    <!--<a class="dropdown-item" href="{% url 'cloned:edit_tweet' tweet.pk %}"></a>-->
  </div>
</span>
{% endif %}

<form action="" method="post" class="form-horizontal">
	{% csrf_token %}
<div class="form-group">
<label for="id_comment_text" class="col-sm-2 control-label">Comment:</label>
<div class="col-sm-8">
<textarea class="form-control" name="comment_text" rows="6" required id="id_comment_text"></textarea>
</div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-info">Comment</button>
    </div>
  </div>
</form>

{% for comment in comments %}
 <div class="comments">
   <p>{{ comment.comment_author }}</p>
   <span><i>{{ comment.comment_text }}</i></span>
 </div>
{% endfor %}

{% endblock content %}

cloned/templates/cloned/add_tweet.html
{% extends 'cloned/base.html' %}
{% block title %}Add a Tweet{% endblock title %}

{% block content %}
<h1>New Tweet</h1>

<form action="" method="post" class="form-horizontal">
	{% csrf_token %}

<div class="form-group">
<label for="id_tweet" class="col-sm-2 control-label">Tweet:</label>
<div class="col-sm-8">
<textarea class="form-control" name="tweet" rows="6" required id="id_tweet"></textarea>
</div>
</div>
 {% if form.errors %}
  <div class="alert alert-danger" role="alert">Your tweet is more than 150 words.</div>
 {% endif %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-info">Tweet</button>
    </div>
  </div>
</form>
{% endblock content %}

cloned/templates/cloned/base.html
{% load static %}

<!doctype html>
<html lang="en">
  {% block head %}
	<head>
	  <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
	  <title>{% block title %}{% endblock title %}</title>
	  <link rel="stylesheet" type="text/css" href="{% static 'cloned/css/bootstrap.min.css' %}"/>
	  <link rel="stylesheet" type="text/css" href="{% static 'cloned/css/style.css' %}"/>
	</head>
  {% endblock head %}
	<body>
		<div class="container row">
		<header>
			
           <div class="header col-sm-6">
             <h2 id="tweet-head"><a href="{% url 'cloned:home' %}">Twitter</a></h2>
           </div>
           <div class="new-tweet col-sm-4">
           	  {% if user.is_authenticated %}
           	    <span><pre><code>Hi {{ user.username }}</code></pre></span>
                <span style="padding-left: 30px"><a href="{% url 'logout' %}"><button class="btn btn-primary">logout</button></a></span>
                <span style="padding-left: 30px"><a href="{% url 'cloned:add_tweet' %}"><button class="btn btn-primary">Tweet</button></a></span> 
               {% else %}
                 <span><a href="{% url 'login' %}"><button type="button" class="btn btn-primary">Login</button></a></span>
                 <span style="padding-left: 30px"><a href="{% url 'accounts:signup' %}"><button class="btn btn-primary">SignUp</button></a></span>
               {% endif %}
              
            </div>
		</header>
		<div class="tweet-container col-md-12">
			{% block content %}{% endblock content %}
		</div>
      </div>


      <script src="{% static 'cloned/js/jquery.min.js' %}"></script>
      <script src="{% static 'cloned/js/bootstrap.min.js' %}"></script>
	</body>
</html>

cloned/templates/cloned/home.html
{% extends 'cloned/base.html' %}

{% block title %}A twitter Clone{% endblock title %}
{% block content %}
{% for tweet in tweets %}
<div class="tweet col-sm-12">
<div class="row">
  <div class="col-sm-8">
	   <p><pre><code>{{ tweet.tweet }}</code></pre></p>
	   <p><strong>{{ tweet.author.username }}</strong> on <em>{{ tweet.date_created }}</em></p>
  </div>
   <div class="col-sm-4">
	   <span class="cmt_btn"><a href="{% url 'cloned:add_comment' tweet.pk %}"><button class="btn btn-primary">Comment</button></a></span>
	  <!--  <span>
	   	{% if user in tweet.liker %}
	    <form action="{% url 'cloned:tweet_like' tweet.pk %}" method="post" style='display:inline;'>
	  	{% csrf_token %}
	  	<a href="{% url 'cloned:unlike' tweet.pk %}"><button class="btn btn-primary" type="submit">
           Likes <span class="badge">{{ like }}</span>
        </button></a>
        {% else %}
        <a href="{% url 'cloned:like' tweet.pk %}"><button class="btn btn-primary" type="submit">
           Likes <span class="badge">{{ like }}</span>
        </button></a>
        {% endif %}
	   </form>
	</span> -->
   </div>
  </div>
</div>
{% endfor %}
{% endblock content %}

cloned/templates/cloned/tweet_delete.html
{% extends 'cloned/base.html' %}
{% block content %}
<h1>Delete Tweet</h1>
<form action="" method="post">{% csrf_token %}
	<p>Are you sure you want to delete</p>
     <p>"{{ tweet.tweet }}"</p>
	<input type="submit" value="Delete"/>
</form>
{% endblock %}

cloned/templates/cloned/tweet_edit.html
{% extends 'cloned/base.html' %}
{% block content %}
<h1>Edit Tweet</h1>
<form action="" method="post">
{% csrf_token %}
<div class="form-group">
<label for="id_tweet" class="col-sm-2 control-label">Tweet:</label>
<div class="col-sm-6">
<textarea class="form-control" name="tweet" rows="4" required id="id_tweet">
	{{ tweet.tweet }}
</textarea>
</div>
</div>
 {% if form.errors %}
 <div class="alert alert-danger" role="alert">Your tweet is more than 150 words.</div>
 {% endif %}

<div class="form-group">
    <div class="col-sm-offset-6 col-sm-10">
      <button type="submit" class="btn btn-info">Update</button>
    </div>
  </div>
</form>
{% endblock content %}